version: '3.3'

services:
  redatorfreelanceronline:
    build: ./build
    container_name: redatorfreelanceronline
    ports:
      - 80
    volumes:
      - ./public:/var/www/html
      - ./logs:/var/logs
    restart: always
    environment:
      VIRTUAL_HOST: redatorfreelanceronline.test
      WORDPRESS_DB_HOST: 192.168.99.100:3307
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

networks:
  default:
    external: 
      name: nginx-proxy