version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    environment: 
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  db: 
    build: ./mysql
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devx3
      MYSQL_USER: er!666#MY
      MYSQL_ROOT_HOST: '%'
      
volumes:
  db_data:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  default:
    external: 
      name: nginx-proxy