version: '3.3'

services:
  rfo:
    build: ./build
    container_name: rfo
    ports:
      - 80
      - 443
    volumes:
      - ./public:/var/www/redatorfreelanceronline.test/public
    environment:
      VIRTUAL_HOST: redatorfreelanceronline.test
      APACHE_SERVERNAME: redatorfreelanceronline.test
      APACHE_LOG_DIR: /var/www/html/log
      LETSENCRYPT_HOST: redatorfreelanceronline.test
      WORDPRESS_DB_HOST: 192.168.99.100:3307
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

networks:
  default:
    external: 
      name: nginx-proxy